#
# Makefile to build animal-i2c driver for Linux using `kbuild' build system
#


obj-m := animal-i2c.o animal-i2c-usim.o

animal-i2c-objs := i2c_main.o
animal-i2c-usim-objs := i2c_usim.o

ccflags-y := -Wall -Wstrict-prototypes


